### ISSUE TITLE
g3

### ISSUE THREAD

**Issue by wrnrlr** [jamen/klein-rs#1]
Hey, I just saw your project and wanted to let you know I'm working on a simular goal of having PGA3D in rust with [g3](https://github.com/wrnrlr/g3). I use a different technique of just translating the library by hand, its more work but by using core_simd it should also be able to compile to wasm using v128. Most of the work is done, but it could use some testing and docs. In the future I hope to add basic graphics based on webgpu, but that's for when I have more time. Just so you know.

**Comment by jamen** [comment]
Wow nice. Thanks for letting me know! I plan on giving it a try now (I was thinking about making a similar library for my uses) so when I get to that I'll report my results.

the core_simd, wasm, and webgpu idea sounds nice. for now im doing native graphics with `wgpu`. but web is still a target im interested in trying out. if you want some help lmk!

**Comment by jamen** [comment]
Archiving and linking to this project now :+1:
